#!/usr/bin/env bash
#=================================================================================================#
# SET MACHINE
#=================================================================================================#
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     export MACHINE=linux;;
    Darwin*)    export MACHINE=mac;;
    CYGWIN*)    export MACHINE=cygwin;;
    MINGW*)     export MACHINE=minGw;;
    *)          export MACHINE="UNKNOWN:${unameOut}"
esac
#=================================================================================================#
# VARIABLES
#=================================================================================================#
export EMAIL="kremeremichael@gmail.com"
export GITHUB_USERNAME="KremerMichael"
export FIRST_NAME="Michael"
export LAST_NAME="Kremer"
export EMPLOYMENT="Boston University"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

#Add functions to path
if [ -d ~/.shell/bin ]; then
    export PATH="~/.shell/bin:$PATH"
fi

#=================================================================================================#
# BASH SOURCES
#=================================================================================================#
#Store destinations for ssh in ~/.bash/bash_ssh
if [ -f ~/.shell/etc/bash_ssh ]; then
    . ~/.shell/etc/bash_ssh
fi

#Store color setup in ~/.bash/bash_colors and load them with this
if [ -f ~/.shell/etc/colors ]; then
    . ~/.shell/etc/colors
fi

#Store alias definitions in ~/.bash/bash_aliases and load them with this
if [ -f ~/.shell/etc/aliases ]; then
    . ~/.shell/etc/aliases
fi

# Note that bash_ssh is ignored in the git repo,
# It's probably smart to not host ssh usernames and destinations remotely
if [ -f ~/.shell/etc/private ]; then
    . ~/.shell/etc/private
fi

# enable programmable completion features
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
	. /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
	. /etc/bash_completion
    fi
fi
